### ISSUE TITLE
Linux does not support HideAppWindow and ShowAppWindow

### ISSUE THREAD

**Issue by dickens7** [antler119/system_tray#18]
- Linux support HideAppWindow and ShowAppWindow

```text
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method HideAppWindow on channel flutter/system_tray/app_window)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      AppWindow.hide (package:system_tray/src/app_window.dart:25:5)
<asynchronous suspension>

tray_callback id:1
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method ShowAppWindow on channel flutter/system_tray/app_window)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      AppWindow.show (package:system_tray/src/app_window.dart:21:5)
<asynchronous suspension>

tray_callback id:8
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method CloseAppWindow on channel flutter/system_tray/app_window)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      AppWindow.close (package:system_tray/src/app_window.dart:29:5)
<asynchronous suspension>
```

**Comment by antler119** [comment]
try v0.0.8
