### ISSUE TITLE
Unhandled Exception: PlatformException(Bad Arguments, Unable to init system tray, false, null)

### ISSUE THREAD

**Issue by holai** [antler119/system_tray#3]
I have a new problem. When I run a hot reload, I get an error, probably because of double registration

Can you add a judgment mechanism to avoid duplicate registration

![_16275274311011](https://user-images.githubusercontent.com/36557839/127424610-10768fb8-d53a-42d7-826b-42f4d3717f5e.png)

**Comment by holai** [comment]
Double registration will invalidate the tray menu click

**Comment by Vonarian** [comment]
I am having the same issue:
![image](https://user-images.githubusercontent.com/68429735/132103603-880bade9-bf85-4337-8736-24bb3594c977.png)
Refers to same code line:
![image](https://user-images.githubusercontent.com/68429735/132103644-97f5fe6a-82ed-4dee-970b-f082fbd32f55.png)

**Comment by Vonarian** [comment]
@antler119 
Do you have a solution?

**Comment by Vonarian** [comment]
![image](https://user-images.githubusercontent.com/68429735/132108933-0892b1f8-4f66-4d6a-8d8a-3a6257bd2516.png)
And this in build.

**Comment by bilegole** [comment]
I compare the example in source code and the Documents, found the key issue is that add assets configuration in pubspec.yaml

**Comment by darkstarx** [comment]
I think platform errors from the plugin must have more details in their messages.

**Comment by leech001** [comment]
If a similar error occurs, add a dot '.' before the relative path.
```
    String path = platform.isWindows
        ? './assets/icons/app_icon.ico'
        : './assets/icons/phone_book.png';
```

**Comment by ggdream** [comment]
You must declare the icons in `pubspec.yaml`.`flutter`.`assets`, rather than a relative path


| |
gdream
|
|
***@***.***
|
On 2/6/2022 14:53，Bulanov ***@***.***> wrote：

If a similar error occurs, add a dot '.' before the relative path.

    String path = platform.isWindows
        ? './assets/icons/app_icon.ico'
        : './assets/icons/phone_book.png';

**Comment by yoehwan** [comment]
I tried to change png to ico on windonw OS , It does work for me.

**Comment by imjakey** [comment]
I have the same issue, finally I found my error was caused by wrong ico file.

**Comment by iveoles** [comment]
I'm also experiencing this issue on Windows 10. 

I have the assets registered in Pubspec and am able to show the icon in the app 

```    
Image(image: AssetImage('assets/images/app_icon.ico'))
```

```
  String path = Platform.isWindows ? 'assets/images/app_icon.ico' : 'assets/images/app_icon.png';

  final AppWindow appWindow = AppWindow();
  final SystemTray systemTray = SystemTray();

  // We first init the systray menu
  await systemTray.initSystemTray(
    title: "system tray",
    iconPath: path,
  );
```

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Bad Arguments, null, false, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      SystemTray.initSystemTray (package:system_tray/src/tray.dart:47:18)
<asynchronous suspension>
#3      startSystemTray (package:asset_checker/main.dart:140:3)
<asynchronous suspension>
```

**Comment by hpelitebook745G2** [comment]
As for my case, merely changing the extension from .png to .ico didn't work for me. You have to convert the image properly, only then it would work.

**Comment by shubham7112001** [comment]
Here I got the error
 await systemTray.initSystemTray(    
    title: "system tray",
    iconPath: path,
  );

I have also the same issue and finally I got the there is no path related to assets/data/.
By adding this in pubspec.yaml I resolve this issue

**Comment by Voyz** [comment]
Adding this line before `systemTray.initSystemTray` helped me, though I don't really understand why:

```dart
Image(image: AssetImage(path));
```

**Comment by dungeon-slave** [comment]
I today also faced with this problem, developers example in pub dev is uncorrect. You need to create folder assets and move from windows/runner/resources app_icon.ico into it. Also you need to add this asset into your pubspec.yaml. It should look something like this
![изображение](https://github.com/antler119/system_tray/assets/70040363/ab670c17-142b-4963-a430-f8f6f2585731)

**Comment by prunedgedev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

tianxiewuhua, @shaozhengbo, @MaxOng94, @SerafDosSantos, @chcying, @amirrsyed, @ramtntht, @lansexiatian, @IssacQin1006, @BenDerPan, @boomzero, @tobiastotz, @better319, @sting2k1, @laijiexing, @nich0las, @alexmlkvch, @kmss6905, @haeho7, @cestoliv
